name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Firebase CLI
      run: |
        npm install -g firebase-tools

    - name: Login to Firebase
      run: firebase login --no-localhost

    - name: Deploy to Firebase
      run: firebase deploy --only hosting
